define({
    _BASE_BG: {
        children: ["paskeBG"]
    },
    paskeBG: {
        type: "container",
        children: [
            "animBG",
            "backgroundHill",
            "cheekyChickenFront",
            "cheekyChickenFrontG2",
            "cheekyChickenLeftSide",
            "cheekyChickenRightSide",
            "backgroundGrass"
        ]
    },
        animBG: {
            type: "container",
            children: [
                "bunny0BG",
                "bunny1BG",
                "bunny2BG",
                "bunny3BG",
                "bunny4BG",
                "bunny5BG",
                "bunny6BG",
                "chicky0BG",
                "chicky1BG",
                "chicky2BG"
            ],
            portrait: {
                x: 0,
                y: 0
            },
            landscape: {
                x: -130,
                y: -40,
                scale: 0.7
            }
        },
            bunny0BG: {
                type: "sprite",
                x: 49,
                y: 234,
                texture: "bunny",
                scale: 0.7
            },
            bunny1BG: {
                type: "sprite",
                x: 165,
                y: 321,
                texture: "bunny",
                scale: 0.8
            },
            bunny2BG: {
                type: "sprite",
                x: 235,
                y: 375,
                texture: "bunny",
                scale: 0.6
            },
            bunny3BG: {
                type: "sprite",
                x: 372,
                y: 410,
                texture: "bunny",
                scale: 0.7
            },
            bunny4BG: {
                type: "sprite",
                x: 449,
                y: 396,
                texture: "bunny",
                scale: 1.0
            },
            bunny5BG: {
                type: "sprite",
                x: 537,
                y: 462,
                texture: "bunny",
                scale: 0.6
            },
            bunny6BG: {
                type: "sprite",
                x: 590,
                y: 444,
                texture: "bunny",
                scale: 0.7
            },
            chicky0BG: {
                type: "sprite",
                x: 740,
                y: 432,
                texture: "chick",
                scale: {x: -0.7, y: 0.7}
            },
            chicky1BG: {
                type: "sprite",
                x: 896,
                y: 414,
                texture: "chick",
                scale: {x: -0.9, y: 0.9}
            },
            chicky2BG: {
                type: "sprite",
                x: 1200,
                y: 254,
                texture: "chick",
                scale: 1.0
            },
        backgroundHill: {
            type: "sprite",
            portrait: { x: 0, y: 240, texture: "hillside" },
            landscape: { x: -370, y: 21, texture: "hillside" }
        },
        cheekyChickenFront: {
            type: "animatedSprite",
            anchor: 0.5,
            portrait: { x: 100, y: 960 },
            landscape: { x: 80, y: 500 },
            loop: false,
            animationSpeed: 0.5,
            textures: [
                "chickenFront/introfront0001",
                "chickenFront/introfront0002",
                "chickenFront/introfront0003",
                "chickenFront/introfront0004",
                "chickenFront/introfront0005",
                "chickenFront/introfront0006",
                "chickenFront/introfront0007",
                "chickenFront/introfront0008",
                "chickenFront/introfront0009",
                "chickenFront/introfront0010",
                "chickenFront/loopfront0011",
                "chickenFront/loopfront0012",
                "chickenFront/loopfront0013",
                "chickenFront/loopfront0014",
                "chickenFront/loopfront0015",
                "chickenFront/loopfront0016",
                "chickenFront/loopfront0017",
                "chickenFront/loopfront0018",
                "chickenFront/loopfront0019",
                "chickenFront/loopfront0020",
                "chickenFront/loopfront0021",
                "chickenFront/loopfront0022",
                "chickenFront/loopfront0023",
                "chickenFront/loopfront0024",
                "chickenFront/loopfront0025",
                "chickenFront/loopfront0026",
                "chickenFront/loopfront0027",
                "chickenFront/loopfront0028",
                "chickenFront/loopfront0029",
                "chickenFront/loopfront0030",
                "chickenFront/outrofront0031",
                "chickenFront/outrofront0032",
                "chickenFront/outrofront0033",
                "chickenFront/outrofront0034",
                "chickenFront/outrofront0035",
                "chickenFront/outrofront0036",
                "chickenFront/outrofront0037",
                "chickenFront/outrofront0038",
                "chickenFront/outrofront0039",
                "chickenFront/outrofront0040"
            ]
        },
        cheekyChickenFrontG2: {
            type: "animatedSprite",
            anchor: 0.5,
            scale: 0.8,
            portrait: { x: 400, y: 365 },
            landscape: { x: 450, y: 230 },
            loop: false,
            animationSpeed: 0.5,
            textures: [
                "chickenFront/introfront0001",
                "chickenFront/introfront0002",
                "chickenFront/introfront0003",
                "chickenFront/introfront0004",
                "chickenFront/introfront0005",
                "chickenFront/introfront0006",
                "chickenFront/introfront0007",
                "chickenFront/introfront0008",
                "chickenFront/introfront0009",
                "chickenFront/introfront0010",
                "chickenFront/loopfront0011",
                "chickenFront/loopfront0012",
                "chickenFront/loopfront0013",
                "chickenFront/loopfront0014",
                "chickenFront/loopfront0015",
                "chickenFront/loopfront0016",
                "chickenFront/loopfront0017",
                "chickenFront/loopfront0018",
                "chickenFront/loopfront0019",
                "chickenFront/loopfront0020",
                "chickenFront/loopfront0021",
                "chickenFront/loopfront0022",
                "chickenFront/loopfront0023",
                "chickenFront/loopfront0024",
                "chickenFront/loopfront0025",
                "chickenFront/loopfront0026",
                "chickenFront/loopfront0027",
                "chickenFront/loopfront0028",
                "chickenFront/loopfront0029",
                "chickenFront/loopfront0030",
                "chickenFront/outrofront0031",
                "chickenFront/outrofront0032",
                "chickenFront/outrofront0033",
                "chickenFront/outrofront0034",
                "chickenFront/outrofront0035",
                "chickenFront/outrofront0036",
                "chickenFront/outrofront0037",
                "chickenFront/outrofront0038",
                "chickenFront/outrofront0039",
                "chickenFront/outrofront0040"
            ]
        },
        cheekyChickenLeftSide: {
            type: "animatedSprite",
            anchor: 0.5,
            portrait: { x: -20, y: 350 },
            landscape: { x: -10, y: 300 },
            scale: { x: -1, y: 1 },
            loop: false,
            animationSpeed: 0.5,
            textures: [
                "chickenSide/introside0001",
                "chickenSide/introside0002",
                "chickenSide/introside0003",
                "chickenSide/introside0004",
                "chickenSide/introside0005",
                "chickenSide/introside0006",
                "chickenSide/introside0007",
                "chickenSide/introside0008",
                "chickenSide/introside0009",
                "chickenSide/introside0010",
                "chickenSide/loopside0011",
                "chickenSide/loopside0012",
                "chickenSide/loopside0013",
                "chickenSide/loopside0014",
                "chickenSide/loopside0015",
                "chickenSide/loopside0016",
                "chickenSide/loopside0017",
                "chickenSide/loopside0018",
                "chickenSide/loopside0019",
                "chickenSide/loopside0020",
                "chickenSide/loopside0021",
                "chickenSide/loopside0022",
                "chickenSide/loopside0023",
                "chickenSide/loopside0024",
                "chickenSide/loopside0025",
                "chickenSide/loopside0026",
                "chickenSide/loopside0027",
                "chickenSide/loopside0028",
                "chickenSide/loopside0029",
                "chickenSide/loopside0030",
                "chickenSide/outroside0031",
                "chickenSide/outroside0032",
                "chickenSide/outroside0033",
                "chickenSide/outroside0034",
                "chickenSide/outroside0035",
                "chickenSide/outroside0036",
                "chickenSide/outroside0037",
                "chickenSide/outroside0038",
                "chickenSide/outroside0039",
                "chickenSide/outroside0040"
            ]
        },
        cheekyChickenRightSide: {
            type: "animatedSprite",
            anchor: 0.5,
            portrait: { x: 650, y: 400 },
            landscape: { x: 810, y: 300 },
            loop: false,
            animationSpeed: 0.5,
            textures: [
                "chickenSide/introside0001",
                "chickenSide/introside0002",
                "chickenSide/introside0003",
                "chickenSide/introside0004",
                "chickenSide/introside0005",
                "chickenSide/introside0006",
                "chickenSide/introside0007",
                "chickenSide/introside0008",
                "chickenSide/introside0009",
                "chickenSide/introside0010",
                "chickenSide/loopside0011",
                "chickenSide/loopside0012",
                "chickenSide/loopside0013",
                "chickenSide/loopside0014",
                "chickenSide/loopside0015",
                "chickenSide/loopside0016",
                "chickenSide/loopside0017",
                "chickenSide/loopside0018",
                "chickenSide/loopside0019",
                "chickenSide/loopside0020",
                "chickenSide/loopside0021",
                "chickenSide/loopside0022",
                "chickenSide/loopside0023",
                "chickenSide/loopside0024",
                "chickenSide/loopside0025",
                "chickenSide/loopside0026",
                "chickenSide/loopside0027",
                "chickenSide/loopside0028",
                "chickenSide/loopside0029",
                "chickenSide/loopside0030",
                "chickenSide/outroside0031",
                "chickenSide/outroside0032",
                "chickenSide/outroside0033",
                "chickenSide/outroside0034",
                "chickenSide/outroside0035",
                "chickenSide/outroside0036",
                "chickenSide/outroside0037",
                "chickenSide/outroside0038",
                "chickenSide/outroside0039",
                "chickenSide/outroside0040"
            ]
        },
        backgroundGrass: {
            type: "sprite",
            portrait: { x: 0, y: 840, texture: "grass_portrait" },
            landscape: { x: 0, y: 384, texture: "grass_landscape" }
        }
});